### ISSUE TITLE
Kafka broker no available

### ISSUE THREAD

**Issue by dahlan77** [rrqq/eye_of_sauron#2]
Hi rrqq : eye_of_shauron

when i run compiler consumer.py and producer.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/dahlan/cobaweb/eye_of_sauron/src/prediction_producer.py", line 73, in run
    auto_offset_reset="earliest")
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/consumer/group.py", line 340, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/client_async.py", line 231, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/client_async.py", line 848, in check_version
    raise Errors.NoBrokersAvailable()
Traceback (most recent call last):
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/dahlan/cobaweb/eye_of_sauron/src/prediction_producer.py", line 212, in run
    auto_offset_reset="earliest")
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/consumer/group.py", line 340, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/client_async.py", line 231, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/client_async.py", line 848, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/dahlan/cobaweb/eye_of_sauron/src/prediction_producer.py", line 212, in run
    auto_offset_reset="earliest")
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/consumer/group.py", line 340, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/client_async.py", line 231, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/dahlan/cobaweb/DarknetKafkaWorker/kafka-python/kafka/client_async.py", line 848, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

what should I do brother / sister

**Comment by SaddamBInSyed** [comment]
@dahlan77

try to set localhost /127.0.01 instead of  "0.0.0.0"  in consumer / producer.
also pass api_version (0,10,1) as a argument

hope this helps
