### ISSUE TITLE
ImportError: cannot import name 'RoundRobinPartitioner' from 'kafka.partitioner' 

### ISSUE THREAD

**Issue by Tramzi31** [rrqq/eye_of_sauron#4]
i was trying to impliment this project in my win 10 with python 3.10.4 and i'm receiving this error when running 
`python3 run_producers.py' `

Error : 
`Traceback (most recent call last):
  File "C:\Users\tramz\Desktop\eye_of_sauron-master\run_producers.py", line 5, in <module>
    from src.frame_producer import StreamVideo
  File "C:\Users\tramz\Desktop\eye_of_sauron-master\src\frame_producer.py", line 12, in <module>
    from kafka.partitioner import RoundRobinPartitioner, Murmur2Partitioner
ImportError: cannot import name 'RoundRobinPartitioner' from 'kafka.partitioner' (C:\Users\tramz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\kafka\partitioner\__init__.py)`

Any help please !!!

**Comment by sagarparmar881** [comment]
Have you tried on Linux?
